server:
  port: ${SERVER_PORT}

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - optional:file:../../.env[.properties]

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false

  mail:
    host: smtp.naver.com
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD}
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.naver.com
        debug: true

  application:
    name: shop_sparta

  datasource:
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    url: jdbc:mysql://localhost:3307/shop

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    #show-sql: 'true'

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
  level:
    root: info

# S3
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    stack.auto: false
    region.static: ${S3_REGION}
