server:
  port: 8081

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - optional:file:../../.env[.properties]

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  datasource:
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    url: ${DATASOURCE_URL}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com.amazonaws: DEBUG
    com.amazonaws.services.s3: DEBUG